### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by dyou3968** [cmubtg/btg-website#79]
Currently, the UI for the footer is fairly basic. Mailchimp has been integrated into it, but there are still ways that we can improve it.

**Comment by NaincyKumariKnoldus** [comment]
Hey @dyou3968 Can I do this please?

**Comment by dyou3968** [comment]
Hi @NaincyKumariKnoldus. Could you explain your affiliation with the club? Thanks.

**Comment by NaincyKumariKnoldus** [comment]
No, Actually I am not attached to club. I only want to contribute to your project.

**Comment by dyou3968** [comment]
Ok. Can you explain a little about your background? Are you a current student interested in joining the club?

**Comment by NaincyKumariKnoldus** [comment]
I like to do open source contribution on github. Thats why  I want to do this.

**Comment by dyou3968** [comment]
Sure. We're more than happy to have open source contributions for our site. Please make a pull request with your work when you're done and a project maintainer will review it.
